### ISSUE TITLE
Commands for retrieving hosts and services.

### ISSUE THREAD

**Issue by jvarlamova** [Mirantis/Kostyor-cli#5]
It would be useful to add commands for getting a list of hosts and services for a specified cluster. New REST API endpoints for getting services and hosts will be added under Kostyor issue https://github.com/sc68cal/Kostyor/issues/34

Also, it would be useful to have command for getting a list of upgrades for a cluster, as PR https://github.com/sc68cal/Kostyor/pull/39 introduces new REST API endpoint '/clusters/<cluster_id>/upgrades'.

**Comment by sc68cal** [comment]
Fixed with #7
